#!/usr/bin/env python3
"""
V2X Emergency Vehicle Project
Pure MPPI (Model Predictive Path Integral) Lane Keeping with Polynomial Target Tracking

Author: Prathamesh Sathe
"""

import math
import numpy as np

class MPPIConfig:
    def __init__(self):
        self.dt = 0.1
        self.horizon = 15       # N lookahead steps
        self.num_samples = 800  # K parallel rollouts
        self.wheelbase = 0.257  # Q-Car wheelbase
        
        # Actuation physical scale limits
        self.max_steer = math.radians(28.0)
        self.max_accel = 1.5
        self.max_speed = 2.0
        self.min_speed = 0.0
        self.target_speed = 1.2
        
        # MPPI Specific Hyperparameters
        self.lam = 0.1         # Temperature parameter
        self.sigma_accel = 0.4 # Exploration noise for accel
        self.sigma_steer = 0.15 # Exploration noise for steering
        
        # Cost Matrix Weights
        self.w_pos = 15.0
        self.w_speed = 3.0
        self.w_terminal = 20.0
        self.w_obstacle = 100.0

class StaticObstacle:
    def __init__(self, x, y, radius):
        self.x = x
        self.y = y
        self.radius = radius

class MPPIController:
    def __init__(self, cfg: MPPIConfig):
        self.cfg = cfg
        # Mean control sequence buffer initialized over horizon: shape (N, 2)
        # column 0: acceleration, column 1: steering angle
        self.U = np.zeros((self.cfg.horizon, 2))
        
    def solve(self, x0, y0, yaw0, v0, obstacles, poly_coefficients):
        """
        Evaluates K parallel rollouts and rewards trajectories that match
        the path generated by our polynomial curve middle layer.
        """
        K = self.cfg.num_samples
        N = self.cfg.horizon
        dt = self.cfg.dt
        L = self.cfg.wheelbase
        
        # 1. Generate normal random perturbation noise tensors: shape (K, N, 2)
        noise = np.zeros((K, N, 2))
        noise[:, :, 0] = np.random.normal(0, self.cfg.sigma_accel, size=(K, N))
        noise[:, :, 1] = np.random.normal(0, self.cfg.sigma_steer, size=(K, N))
        
        # 2. Broadcast perturbations across current mean control baseline
        perturbed_u = self.U + noise
        
        # Clamp inputs strictly to physical limits
        perturbed_u[:, :, 0] = np.clip(perturbed_u[:, :, 0], -self.cfg.max_accel, self.cfg.max_accel)
        perturbed_u[:, :, 1] = np.clip(perturbed_u[:, :, 1], -self.cfg.max_steer, self.cfg.max_steer)
        
        # 3. Vectorized State Rollout Buffers: shape (K, N+1)
        state_x = np.zeros((K, N + 1))
        state_y = np.zeros((K, N + 1))
        state_yaw = np.zeros((K, N + 1))
        state_v = np.zeros((K, N + 1))
        
        # Seed state matrices with current ground-truth vehicle state
        state_x[:, 0] = x0
        state_y[:, 0] = y0
        state_yaw[:, 0] = yaw0
        state_v[:, 0] = v0
        
        costs = np.zeros(K)
        
        # 4. Process parallel kinematic rollout vector equations forward in time
        for t in range(N):
            accel = perturbed_u[:, t, 0]
            steer = perturbed_u[:, t, 1]
            
            # Step kinematic bicycle vehicle parameters across all K paths at once
            state_x[:, t+1] = state_x[:, t] + state_v[:, t] * np.cos(state_yaw[:, t]) * dt
            state_y[:, t+1] = state_y[:, t] + state_v[:, t] * np.sin(state_yaw[:, t]) * dt
            state_yaw[:, t+1] = state_yaw[:, t] + (state_v[:, t] / L) * np.tan(steer) * dt
            state_v[:, t+1] = np.clip(state_v[:, t] + accel * dt, self.cfg.min_speed, self.cfg.max_speed)
            
            # --- DYNAMIC POLYNOMIAL COST CHECK ---
            # Calculate what the ideal target Y coordinate should be at our current simulated X position
            # Using the standard line formula: target_y = Ax^2 + Bx + C
            target_y = (poly_coefficients[0] * (state_x[:, t+1]**2) + 
                        poly_coefficients[1] * state_x[:, t+1] + 
                        poly_coefficients[2])
            
            # Penalize tracking error relative to the polynomial line
            costs += self.cfg.w_pos * ((state_y[:, t+1] - target_y) ** 2)
            costs += self.cfg.w_speed * ((state_v[:, t+1] - self.cfg.target_speed) ** 2)
            
            # Obstacle proximity penalties (safety net layer)
            for obs in obstacles:
                dist = np.hypot(state_x[:, t+1] - obs.x, state_y[:, t+1] - obs.y)
                safe_zone = obs.radius + 0.35
                costs += (dist < safe_zone) * self.cfg.w_obstacle * (safe_zone - dist) ** 2

        # Terminal state stability anchor penalty
        target_y_end = (poly_coefficients[0] * (state_x[:, -1]**2) + 
                        poly_coefficients[1] * state_x[:, -1] + 
                        poly_coefficients[2])
        costs += self.cfg.w_terminal * ((state_y[:, -1] - target_y_end) ** 2)
        
        # 5. Calculate Stochastic Boltzmann soft-max weights
        beta = np.min(costs) # Normalization factor to prevent numerical overflow
        weights = np.exp(-1.0 / self.cfg.lam * (costs - beta))
        sum_weights = np.sum(weights) + 1e-10
        weights /= sum_weights 
        
        # 6. Update master expectations using cost-weighted noise matrices
        weighted_noise = np.tensordot(weights, noise, axes=(0, 0)) 
        self.U += weighted_noise
        
        # Extract immediate next optimal command step variables
        optimal_accel = self.U[0, 0]
        optimal_steer = self.U[0, 1]
        
        # Shift control horizon queue buffer forward in time
        self.U = np.roll(self.U, -1, axis=0)
        self.U[-1] = self.U[-2]
        
        return optimal_accel, optimal_steer, state_x, state_y

# --- SIMULATION BENCHMARK RUNNER ---
if __name__ == "__main__":
    cfg = MPPIConfig()
    controller = MPPIController(cfg)
    
    # Mock a flat track line polynomial coefficient set: y = 0x^2 + 0x + 0
    # On Tuesday, your curve_generator.py will calculate real dynamic values here!
    mock_poly = np.array([0.0, 0.0, 0.0])
    obstacles = []
    
    x, y, yaw, v = 0.0, 0.0, 0.0, 0.0
    print("Running newly structured MPPI controller verification...")
    
    accel, steer, rx, ry = controller.solve(x, y, yaw, v, obstacles, mock_poly)
    print(f"Success! Next optimal inputs calculated successfully -> Accel: {accel:.2f}, Steer: {steer:.2f}")